### ISSUE TITLE
HURL plugin incompatible with IntelliJ IDEA 2024.3

### ISSUE THREAD

**Issue by luolong** [jazzytomato/intellij-hurl-plugin#37]
Upgraded to IntelliJ IDEA 2024.3 yesterday and Intellij HURL plugin declared itself incompatible with it and was disabled by IntelliJ.

**Comment by jazzytomato** [comment]
Hi, thanks for reporting. I will upgrade the plugin in the next few days!

**Comment by luolong** [comment]
Thanks, I tried to make a PR myself, but just lacked time to get dev environment set up poperly...

**Comment by luolong** [comment]
👏🏻 👏🏻 👏🏻
