### ISSUE TITLE
Plugin attempts to find hurl executable in homebrew folder outside of homebrew environments

### ISSUE THREAD

**Issue by Annoiiyed** [jazzytomato/intellij-hurl-plugin#44]
Hi! Thank you for your efforts in this. I noticed that, while running arch, the plugin is attempting to run `/opt/homebrew/bin/hurl`, however, that is only a relevant path when having Hurl installed through Homebrew.

On my machine, for example, the location of the hurl executable is the (fairly common) `/usr/bin/hurl`

Perhaps this should be configurable, and contain some common fallback paths?

**Comment by phunguyen19** [comment]
You can update it in "Edit configuration template...", after that new run of Hurl will use the new setup

<img width="803" alt="Screenshot 2024-12-24 at 20 54 35" src="https://github.com/user-attachments/assets/9494a410-985d-4f5f-9ee4-0e01ab8e4238" />

**Comment by Annoiiyed** [comment]
Ah, I see! Thank you
